### ISSUE TITLE
Try to figure out game mechanics programmatically

### ISSUE THREAD

**Issue by Windfisch** [Windfisch/agario-frickel#13]
Automatically try to create stats about:

[x] (std deviation of "moving direction - ejected mass direction") vs movement speed, movement change, etc.
    expectation: stddev is about 10 deg

[x] (ejected mass distance) vs size, movementspeed
    expectation: distance = size+700

[x] (own mass) vs (visible world window)

[x] (cell  mass) vs (cell speed)

[ ] (cell mass or speed) vs (speed / deceleration of split cell)

[x] (??) vs (time until split cells merge again)

[x] (virus sizes) vs (how many shoots to explode)

[x] ?? vs (how far does a split virus fly?)

**Comment by Gjum** [comment]
This is something I have been wanting to do for a long time, but never got around to doing it.

You could do this by creating a [subscriber logging cell data](https://github.com/Gjum/gagar/blob/89ef65e2d2ea200c1b0234f4e819aca02f745b09/gagar/draw_hud.py#L59-L75), which you then connect to the client via a [MultiSubscriber](https://github.com/Gjum/gagar/blob/89ef65e2d2ea200c1b0234f4e819aca02f745b09/gagar/subscriber.py#L12).

Your current `EnhancingSubscriber` could then be plugged in there as well.

This way, I could also use your logging subscriber in [`gagar`](https://github.com/Gjum/gagar/#gagar) to gather even more data, and maybe send it automatically from all users to a collection server.

**Comment by Windfisch** [comment]
is the world_update_post callback the appropriate callback for continously logging data? I.e., is he called at a constant rate?

Or will i need to register to additional callbacks?

**Comment by Gjum** [comment]
I really need to write some proper documentation when I have more time for this project. At the moment, the best thing you can do is to search in `client.py` for `self.subscriber.on_`.

When the server sends a `world_update`, the client first emits `world_update_pre`, then all the cell related stuff while updating the world state, and then finally emits `world_update_post`.

So `world_update_post` is emitted at the same rate as `world_update_pre`, the difference is that the world changes are applied in between. This means you can for example back up the world state on the `pre` event, and log the world state on the `post` event.

**Comment by Windfisch** [comment]
A comprehensive summary of the game mechanics (as of 2015-09-01) can be found under:

https://github.com/Windfisch/agario-frickel/blob/4251e85c172f57c39bdfa244e945578eb450926d/reversing_game_mechanics/game_mechanics.txt

**Comment by Gjum** [comment]
So you did not notice that ejected mass loses 1 mass after a certain amount of time?

**Comment by Windfisch** [comment]
oh. wat :D?
no i did not, thanks :D

(however, this does not feel very important for the bot behaviour)
