### ISSUE TITLE
Division by zero / crash when split

### ISSUE THREAD

**Issue by Windfisch** [Windfisch/agario-frickel#2]
Traceback (most recent call last):
  File "main.py", line 57, in <module>
    corridor_width = 2 \* math.asin(cell.size / dist)
ValueError: math domain error

This probably happens when our center is exactly over something, but because we're split, we didn't eat it yet. Then dist is 0, _poof_

**Comment by SpitfireX** [comment]
WINDFISCH FIX YOUR MATH!!!111!1!!

**Comment by Windfisch** [comment]
fixed in ec5409a1f1467895af7ebed239bcabb7f3dd2a0c
