### ISSUE TITLE
Don't even try to eat / chase food if a larger cell is near that food

### ISSUE THREAD

**Issue by Windfisch** [Windfisch/agario-frickel#6]
To avoid oscillating between "but i want this food!!" and "eww a larger cell, let's run away"

**Comment by SpitfireX** [comment]
Won't be a reliable fix. Often the food target is relatively close by the cell but the pathing gets interrupted by a threat that's farther away. Maybe try excluding food in the current/last forbidden_intervals?

**Comment by Windfisch** [comment]
implemented some time ago
